version: '3'

services: 
  server: 
    build: ./server
    expose: 
      - "4000"
    ports: 
      - "4000:4000"
    command: yarn start

  front:
    build: .
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    command: yarn start
    depends_on:
      - server 